<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=shift-jis">
  <title>例外(exceptions)</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="language.namespaces.faq.html">≪ FAQ: 名前空間について知っておくべきこと</a></li>
      <li style="float: right;"><a href="language.exceptions.extending.html">例外を拡張する ≫</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="langref.html">言語リファレンス</a></li>
    <li>例外(exceptions)</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="language.exceptions" class="chapter">
 <h1>例外(exceptions)</h1>
<h2>目次</h2><ul class="chunklist chunklist_chapter"><li><a href="language.exceptions.extending.html">例外を拡張する</a></li></ul>


 <p class="para">
  PHP 5 は、他のプログラミング言語に似た例外モデルを有しています。
  PHP 内で例外が投げられ (&quot;<em>throw</em>&quot; され)、それが
  捕捉され (&quot;<em>catch</em>&quot; され) ます。発生した例外を
  捕捉するには、コードを <em>try</em> ブロックで囲みます。
  各 <em>try</em> ブロックには、対応する <em>catch</em>
  ブロックが存在する必要があります。異なる型の例外を捕捉するために
  複数の <em>catch</em> フロックを使用することができます。
  通常の実行時 (<em>try</em> ブロック内で例外が投げられなかった
  場合、あるいは投げられた例外に対応する <em>catch</em>
  ブロックが存在しなかった場合) は、<em>catch</em>
  ブロック内は処理されず、それ以降から処理が続けられます。
  <em>catch</em> ブロックの中から例外を投げる
  (あるいは投げなおす) こともできます。
 </p>
 <p class="para">
  例外が投げられた場合、その命令に続くコードは実行されず、
  PHP は最初にマッチする <em>catch</em> ブロックを探します。
  例外が捕捉されない場合、PHP は &quot;<em>Uncaught Exception ...</em>&quot;
  というメッセージとともに
  致命的なエラー(fatal error)を発行します。
  ただし、<span class="function"><a href="function.set-exception-handler.html" class="function">set_exception_handler()</a></span> でハンドラが
  定義されている場合を除きます。
 </p>
  <p class="para">
   PHP 5.5 以降では、<em>catch</em> ブロックの後に
   <em>finally</em> ブロックも指定できるようになりました。
   <em>finally</em> ブロックの何かに書いたコードは、
   <em>try</em> および <em>catch</em> ブロックの後で常に実行されます。
   例外がスローさされたかどうかには関係ありません。
   <em>finally</em> ブロックを実行してから、通常の処理を続行します。
  </p>
  <p class="para">
   スローされるオブジェクトは、<a href="class.exception.html" class="classname">Exception</a> クラスあるいは
   <a href="class.exception.html" class="classname">Exception</a> のサブクラスのインスタンスでなければなりません。
   それ以外のオブジェクトをスローしようとすると
   PHP の Fatal Error が発生します。
  </p>
  <blockquote class="note"><p><strong class="note">注意</strong>: 
   <p class="para">
    PHP の内部関数の多くは
    <a href="errorfunc.configuration.html#ini.error-reporting" class="link">エラー報告</a>
    を使っており、例外を使っているのは新しい
    <a href="language.oop5.html" class="link">オブジェクト指向</a>
    の拡張モジュールのみです。
    しかし、<a href="class.errorexception.html" class="link">ErrorException</a>
    を使えば簡単にエラーを例外に変換することができます。
   </p>
  </p></blockquote>
  <div class="tip"><strong class="tip">ヒント</strong>
   <p class="para">
    <a href="intro.spl.html" class="link">Standard PHP Library (SPL)</a>
    には<a href="spl.exceptions.html" class="link">組み込みの例外</a>が数多く用意されています。
   </p>
  </div>
 <div class="example" id="example-287">
  <p><strong>例1 例外を投げるには</strong></p>
  <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'ゼロによる除算。'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;実行は継続される<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
  </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
捕捉した例外: ゼロによる除算。
Hello World
</pre></div>
    </div>
 </div>
   <div class="example" id="example-288">
    <p><strong>例2 例外処理での <em>finally</em> ブロック</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(!</span><span style="color: #0000BB">$x</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'ゼロによる除算。'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;</span><span style="color: #0000BB">1</span><span style="color: #007700">/</span><span style="color: #0000BB">$x</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">5</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"First&nbsp;finally.\n"</span><span style="color: #007700">;<br />}<br /><br />try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #0000BB">inverse</span><span style="color: #007700">(</span><span style="color: #0000BB">0</span><span style="color: #007700">)&nbsp;.&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">'捕捉した例外:&nbsp;'</span><span style="color: #007700">,&nbsp;&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}&nbsp;finally&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Second&nbsp;finally.\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #FF8000">//&nbsp;処理を続行します<br /></span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;World\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
0.2
First finally.
捕捉した例外: ゼロによる除算。
Second finally.
Hello World
</pre></div>
    </div>
   </div>
   <div class="example" id="example-289">
    <p><strong>例3 ネストした例外</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /><br /></span><span style="color: #007700">class&nbsp;</span><span style="color: #0000BB">MyException&nbsp;</span><span style="color: #007700">extends&nbsp;</span><span style="color: #0000BB">Exception&nbsp;</span><span style="color: #007700">{&nbsp;}<br /><br />class&nbsp;</span><span style="color: #0000BB">Test&nbsp;</span><span style="color: #007700">{<br />&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;</span><span style="color: #0000BB">testing</span><span style="color: #007700">()&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw&nbsp;new&nbsp;</span><span style="color: #0000BB">MyException</span><span style="color: #007700">(</span><span style="color: #DD0000">'foo!'</span><span style="color: #007700">);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">MyException&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #FF8000">//&nbsp;改めてスロー<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">throw&nbsp;</span><span style="color: #0000BB">$e</span><span style="color: #007700">;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;catch&nbsp;(</span><span style="color: #0000BB">Exception&nbsp;$e</span><span style="color: #007700">)&nbsp;{<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #0000BB">var_dump</span><span style="color: #007700">(</span><span style="color: #0000BB">$e</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">());<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br />&nbsp;&nbsp;&nbsp;&nbsp;}<br />}<br /><br /></span><span style="color: #0000BB">$foo&nbsp;</span><span style="color: #007700">=&nbsp;new&nbsp;</span><span style="color: #0000BB">Test</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">$foo</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">testing</span><span style="color: #007700">();<br /><br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

    <div class="example-contents"><p>上の例の出力は以下となります。</p></div>
    <div class="example-contents screen">
<div class="cdata"><pre>
string(4) &quot;foo!&quot;
</pre></div>
    </div>
   </div>
 
 

 </div>
<div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="115257""></a>
  <div class="note">
   <strong class="user">Hayley Watson</strong>
   <a href="#115257" class="date">23-Jun-2014 03:58</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Remember that Exceptions are also objects and can be handled as such; they can be constructed in and returned as values from functions, passed as arguments to other functions, and examined before being thrown. You don't have to throw it as soon as you have constructed it (the stack trace will of course reflect the moment the Exception was constructed, not the moment it was thrown).<br />
<br />
You might, for example, want to collect additional information to include in YourException but you don't want to clutter up the YourException class or the code containing the "throw" statement by collecting the information there. Or you might want to do something (such as logging) with each Exception that is thrown from a certain region (catch it, pass it to the logging function, then rethrow it).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="115240""></a>
  <div class="note">
   <strong class="user">telefoontoestel at nospam dot org</strong>
   <a href="#115240" class="date">18-Jun-2014 09:34</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
When using finally keep in mind that when a exit/die statement is used in the catch block it will NOT go through the finally block. <br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />
} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />
} finally {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="comment">// try block<br />
// catch block<br />
// finally block<br />
</span><span class="default">?&gt;<br />
</span><br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"try block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"test"</span><span class="keyword">);<br />
} catch (</span><span class="default">Exception $ex</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"catch block&lt;br /&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; exit(</span><span class="default">1</span><span class="keyword">);<br />
} finally {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"finally block&lt;br /&gt;"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="comment">// try block<br />
// catch block<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="114207""></a>
  <div class="note">
   <strong class="user">php at marcuspope dot com</strong>
   <a href="#114207" class="date">25-Jan-2014 02:42</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Using a return statement inside a finally block will override any other return statement or thrown exception from the try block and all defined catch blocks.&nbsp;&nbsp; Code execution in the parent stack will continue as if the exception was never thrown.&nbsp; <br />
<br />
Frankly this is a good design decision because it means I can optionally dismiss all thrown exceptions from 1 or more catch blocks in one place, without having to nest my whole try block inside an additional (and otherwise needless) try/catch block.<br />
<br />
This is the same behavior as Java, whereas C# throws a compile time error when a return statement exists inside a finally block.&nbsp; So I figured it was worth pointing out to PHP devs who may not have any exposure to finally blocks or how other languages do it.<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">function </span><span class="default">asdf</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'error'</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"An error occurred"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw </span><span class="default">$e</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">//This overrides the exception as if it were never thrown<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">return </span><span class="string">"\nException erased"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="default">asdf</span><span class="keyword">();<br />
}<br />
catch(</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"\nResult: " </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
The output from above will look like this:<br />
<br />
&nbsp;&nbsp;&nbsp; An error occurred<br />
&nbsp;&nbsp;&nbsp; Exception erased<br />
<br />
Without the return statement in the finally block it would look like this:<br />
<br />
&nbsp;&nbsp;&nbsp; An error occurred<br />
&nbsp;&nbsp;&nbsp; Result: error</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="113368""></a>
  <div class="note">
   <strong class="user">cyrus+php at boadway dot ca</strong>
   <a href="#113368" class="date">02-Oct-2013 11:50</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
There's some inconsistent behaviour associated with PHP 5.5.3's finally and return statements. If a method returns a variable in a try block (e.g. return $foo;), and finally modifies that variable, the /modified/ value is returned. However, if the try block has a return that has to be evaluated in-line (e.g. return $foo+0;), finally's changes to $foo will /not/ affect the return value.<br />
<br />
[code]<br />
function returnVariable(){<br />
&nbsp;&nbsp;&nbsp; $foo = 1;<br />
&nbsp;&nbsp;&nbsp; try{<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return $foo;<br />
&nbsp;&nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $foo++;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
function returnVariablePlusZero(){<br />
&nbsp;&nbsp;&nbsp; $foo = 1;<br />
&nbsp;&nbsp;&nbsp; try{<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return $foo + 0;<br />
&nbsp;&nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $foo++;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
$test1 = returnVariable(); // returns 2, not the correct value of 1.<br />
$test2 = returnVariablePlusZero(); // returns correct value of 1, but inconsistent with $test1.<br />
[/code]<br />
<br />
It looks like it's trying to be efficient by not allocating additional memory for the return value when it thinks it doesn't have to, but the spec is that finally is run after try is completed execution, and that includes the evaluation of the return expression.<br />
<br />
One could argue (weakly) that the first method should be the correct result, but at least the two methods should be consistent.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="113328""></a>
  <div class="note">
   <strong class="user">jim at anderos dot com</strong>
   <a href="#113328" class="date">28-Sep-2013 02:22</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you are using a namespace, you must indicate the global namespace when using Exceptions.<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">namespace </span><span class="default">alpha</span><span class="keyword">;<br />
function </span><span class="default">foo</span><span class="keyword">(){<br />
&nbsp;&nbsp;&nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Something is wrong!"</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// throw new Exception(""); will fail<br />
</span><span class="keyword">}<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">foo</span><span class="keyword">();<br />
} catch( \</span><span class="default">Exception $e </span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// catch( Exception $e ) will give no warning, but will not catch Exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">echo </span><span class="string">"ERROR: </span><span class="default">$e</span><span class="string">"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112529""></a>
  <div class="note">
   <strong class="user">sander at rotorsolutions dot nl</strong>
   <a href="#112529" class="date">26-Jun-2013 11:08</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Just an example why finally blocks are usefull (5.5)<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="comment">//without catch<br />
</span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//do something that throws an exeption<br />
&nbsp; </span><span class="keyword">}<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br />
&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
function </span><span class="default">example2</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; </span><span class="comment">//open sql connection check user as example<br />
&nbsp;&nbsp; &nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">false</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp; }<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br />
&nbsp; </span><span class="keyword">}<br />
}</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112528""></a>
  <div class="note">
   <strong class="user">sander at rotorsolutions dot nl</strong>
   <a href="#112528" class="date">26-Jun-2013 11:06</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Just an example why finally blocks are usefull (5.5)<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="comment">//without catch<br />
</span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//do something that throws an exeption<br />
&nbsp; </span><span class="keyword">}<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br />
&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
function </span><span class="default">example2</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; </span><span class="comment">//open sql connection check user as example<br />
&nbsp;&nbsp; &nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">false</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp; }<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br />
&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112527""></a>
  <div class="note">
   <strong class="user">sander at rotorsolutions dot nl</strong>
   <a href="#112527" class="date">26-Jun-2013 11:05</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Just an example why finally blocks are usefull (5.5)<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="comment">//without catch<br />
</span><span class="keyword">function </span><span class="default">example</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//do something that throws an exeption<br />
&nbsp; </span><span class="keyword">}<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//this code will be executed even when the exception is executed<br />
&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
function </span><span class="default">example2</span><span class="keyword">() {<br />
&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; </span><span class="comment">//open sql connection check user as example<br />
&nbsp;&nbsp; &nbsp; </span><span class="keyword">if(</span><span class="default">condition</span><span class="keyword">) { <br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">false</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp; }<br />
&nbsp; finally {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">//close the sql connection, this will be executed even if the return is called.<br />
&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112507""></a>
  <div class="note">
   <strong class="user">Edu</strong>
   <a href="#112507" class="date">25-Jun-2013 03:13</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
The "finally" block can change the exception that has been throw by the catch block.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try{<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Hello"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } catch(\</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch in\n"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw </span><span class="default">$e</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } finally {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" finally \n"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new \</span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Bye"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
} catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" catch out\n"</span><span class="keyword">;<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
The output is:<br />
<br />
Hello catch in<br />
Hello finally <br />
Bye catch out</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="106696""></a>
  <div class="note">
   <strong class="user">Sawsan</strong>
   <a href="#106696" class="date">29-Nov-2011 06:36</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
the following is an example of a re-thrown exception and the using of getPrevious function:<br />
<br />
<span class="default">&lt;?php<br />
<br />
$name </span><span class="keyword">= </span><span class="string">"Name"</span><span class="keyword">;<br />
<br />
</span><span class="comment">//check if the name contains only letters, and does not contain the word name<br />
<br />
</span><span class="keyword">try<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp; try<br />
&nbsp;&nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp;&nbsp; if (</span><span class="default">preg_match</span><span class="keyword">(</span><span class="string">'/[^a-z]/i'</span><span class="keyword">, </span><span class="default">$name</span><span class="keyword">)) <br />
&nbsp;&nbsp; &nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains character other than a-z A-Z"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; }&nbsp;&nbsp; <br />
&nbsp;&nbsp; &nbsp; &nbsp; if(</span><span class="default">strpos</span><span class="keyword">(</span><span class="default">strtolower</span><span class="keyword">(</span><span class="default">$name</span><span class="keyword">), </span><span class="string">'name'</span><span class="keyword">) !== </span><span class="default">FALSE</span><span class="keyword">)<br />
&nbsp;&nbsp; &nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"</span><span class="default">$name</span><span class="string"> contains the word name"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp; echo </span><span class="string">"The Name is valid"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; catch(</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp; &nbsp; {<br />
&nbsp;&nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"insert name again"</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; }<br />
&nbsp;<br />
catch (</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp; if (</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">())<br />
&nbsp;&nbsp; {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="string">"The Previous Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getPrevious</span><span class="keyword">()-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp; }<br />
&nbsp;&nbsp; echo </span><span class="string">"The Exception is: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">"&lt;br/&gt;"</span><span class="keyword">;<br />
&nbsp;&nbsp; }<br />
<br />
&nbsp;</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="105102""></a>
  <div class="note">
   <strong class="user">alex dowgailenko [at] g mail . com</strong>
   <a href="#105102" class="date">27-Jul-2011 09:20</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you use the set_error_handler() to throw exceptions of errors, you may encounter issues with __autoload() functionality saying that your class doesn't exist and that's it.<br />
<br />
If you do this:<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">class </span><span class="default">MyException </span><span class="keyword">extends </span><span class="default">Exception<br />
</span><span class="keyword">{<br />
}<br />
<br />
class </span><span class="default">Tester<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">foobar</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; try<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">helloWorld</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; } catch (</span><span class="default">MyException $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Problem in foobar'</span><span class="keyword">,</span><span class="default">0</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; protected function </span><span class="default">helloWorld</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">MyException</span><span class="keyword">(</span><span class="string">'Problem in helloWorld()'</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
</span><span class="default">$tester </span><span class="keyword">= new </span><span class="default">Tester</span><span class="keyword">;<br />
try<br />
{<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$tester</span><span class="keyword">-&gt;</span><span class="default">foobar</span><span class="keyword">();<br />
} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">();<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
The trace will only show $tester-&gt;foobar() and not the call made to $tester-&gt;helloWorld().<br />
<br />
In other words, if you pass a previous exception to a new one, the previous exception's stack trace is taken into account in the new exception.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="103819""></a>
  <div class="note">
   <strong class="user">Johan</strong>
   <a href="#103819" class="date">05-May-2011 10:18</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Custom error handling on entire pages can avoid half rendered pages for the users:<br />
<br />
<span class="default">&lt;?php<br />
ob_start</span><span class="keyword">();<br />
try {<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">/*contains all page logic <br />
&nbsp;&nbsp;&nbsp; and throws error if needed*/<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">...<br />
} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp; </span><span class="default">ob_end_clean</span><span class="keyword">();<br />
&nbsp; </span><span class="default">displayErrorPage</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br />
}<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="97963""></a>
  <div class="note">
   <strong class="user">zmunoz at gmail dot com</strong>
   <a href="#97963" class="date">18-May-2010 10:05</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
When catching an exception inside a namespace it is important that you escape to the global space:<br />
<br />
<span class="default">&lt;?php<br />
&nbsp;</span><span class="keyword">namespace </span><span class="default">SomeNamespace</span><span class="keyword">;<br />
<br />
&nbsp;class </span><span class="default">SomeClass </span><span class="keyword">{<br />
<br />
&nbsp; function </span><span class="default">SomeFunction</span><span class="keyword">() {<br />
&nbsp;&nbsp; try {<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Some Error Message'</span><span class="keyword">);<br />
&nbsp;&nbsp; } catch (\</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">var_dump</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br />
&nbsp;&nbsp; }<br />
&nbsp; }<br />
<br />
&nbsp;}<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="91159""></a>
  <div class="note">
   <strong class="user">ask at nilpo dot com</strong>
   <a href="#91159" class="date">27-May-2009 09:19</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you intend on creating a lot of custom exceptions, you may find this code useful.&nbsp; I've created an interface and an abstract exception class that ensures that all parts of the built-in Exception class are preserved in child classes.&nbsp; It also properly pushes all information back to the parent constructor ensuring that nothing is lost.&nbsp; This allows you to quickly create new exceptions on the fly.&nbsp; It also overrides the default __toString method with a more thorough one.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">interface </span><span class="default">IException<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">/* Protected methods inherited from Exception class */<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getMessage</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message <br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getCode</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// User-defined Exception code<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getFile</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getLine</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getTrace</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// An array of the backtrace()<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">getTraceAsString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Formated string of trace<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; /* Overrideable methods inherited from Exception class */<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__toString</span><span class="keyword">();&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// formated string for display<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">);<br />
}<br />
<br />
abstract class </span><span class="default">CustomException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">implements </span><span class="default">IException<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; protected </span><span class="default">$message </span><span class="keyword">= </span><span class="string">'Unknown exception'</span><span class="keyword">;&nbsp; &nbsp;&nbsp; </span><span class="comment">// Exception message<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$string</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Unknown<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$code&nbsp; &nbsp; </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// User-defined exception code<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$file</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source filename of exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">protected </span><span class="default">$line</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// Source line of exception<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">private&nbsp;&nbsp; </span><span class="default">$trace</span><span class="keyword">;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Unknown<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$code </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if (!</span><span class="default">$message</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">$this</span><span class="keyword">(</span><span class="string">'Unknown '</span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">));<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__toString</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">) . </span><span class="string">" '</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">message</span><span class="keyword">}</span><span class="string">' in </span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">file</span><span class="keyword">}</span><span class="string">(</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">line</span><span class="keyword">}</span><span class="string">)\n"<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">. </span><span class="string">"</span><span class="keyword">{</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">()}</span><span class="string">"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
Now you can create new exceptions in one line:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">TestException </span><span class="keyword">extends </span><span class="default">CustomException </span><span class="keyword">{}<br />
</span><span class="default">?&gt;<br />
</span><br />
Here's a test that shows that all information is properly preserved throughout the backtrace.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">exceptionTest</span><span class="keyword">()<br />
{<br />
&nbsp;&nbsp;&nbsp; try {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">TestException</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; catch (</span><span class="default">TestException $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"Caught TestException ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"Caught Exception ('</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()}</span><span class="string">')\n</span><span class="keyword">{</span><span class="default">$e</span><span class="keyword">}</span><span class="string">\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
echo </span><span class="string">'&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">exceptionTest</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br />
</span><span class="default">?&gt;<br />
</span><br />
Here's a sample output:<br />
<br />
Caught TestException ('Unknown TestException')<br />
TestException 'Unknown TestException' in C:\xampp\htdocs\CustomException\CustomException.php(31)<br />
#0 C:\xampp\htdocs\CustomException\ExceptionTest.php(19): CustomException-&gt;__construct()<br />
#1 C:\xampp\htdocs\CustomException\ExceptionTest.php(43): exceptionTest()<br />
#2 {main}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="86476""></a>
  <div class="note">
   <strong class="user">Shot (Piotr Szotkowski)</strong>
   <a href="#86476" class="date">21-Oct-2008 09:13</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
'Normal execution (when no exception is thrown within the try block, *or when a catch matching the thrown exception's class is not present*) will continue after that last catch block defined in sequence.'<br />
<br />
'If an exception is not caught, a PHP Fatal Error will be issued with an "Uncaught Exception ..." message, unless a handler has been defined with set_exception_handler().'<br />
<br />
These two sentences seem a bit contradicting about what happens 'when a catch matching the thrown exception's class is not present' (and the second sentence is actually correct).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="81960""></a>
  <div class="note">
   <strong class="user">michael dot ochs at gmx dot net</strong>
   <a href="#81960" class="date">21-Mar-2008 12:44</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Actually it isn't possible to do:<br />
<span class="default">&lt;?php<br />
someFunction</span><span class="keyword">() OR throw new </span><span class="default">Exception</span><span class="keyword">();<br />
</span><span class="default">?&gt;<br />
</span><br />
This leads to a T_THROW Syntax Error. If you want to use this kind of exceptions, you can do the following:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">throwException</span><span class="keyword">(</span><span class="default">$message </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">,</span><span class="default">$code </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">) {<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">,</span><span class="default">$code</span><span class="keyword">);<br />
}<br />
<br />
</span><span class="default">someFunction</span><span class="keyword">() OR </span><span class="default">throwException</span><span class="keyword">();<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="81603""></a>
  <div class="note">
   <strong class="user">chugadie dot geo at yahoo dot com</strong>
   <a href="#81603" class="date">05-Mar-2008 07:40</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
@webmaster at asylum-et dot com<br />
<br />
What Mo is describing is bug 44053 (<a href="http://bugs.php.net/bug.php?id=44053" rel="nofollow" target="_blank">http://bugs.php.net/bug.php?id=44053</a>) in which exceptions cannot be caught if you are using a custom error handler to catch warnings, notices, etc.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="79577""></a>
  <div class="note">
   <strong class="user">omnibus at omnibus dot edu dot pl</strong>
   <a href="#79577" class="date">04-Dec-2007 12:11</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Just to be more precise in what Frank found:<br />
Catch the exceptions always in order from the bottom to the top of the Exception and subclasses class hierarchy. If you have class MyException extending Exception and class My2Exception extending MyException always catch My2Exception before MyException.<br />
<br />
Hope this helps</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="78591""></a>
  <div class="note">
   <strong class="user">hartym dot dont dot like dot spam at gmail dot com</strong>
   <a href="#78591" class="date">18-Oct-2007 01:41</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
@serenity: of course you need to throw exception within the try block, catch will not watch fatal errors, nor less important errors but only exceptions that are instanceof the exception type you're giving. Of course by within the try block, i mean within every functions call happening in try block.<br />
<br />
For example, to nicely handle old mysql errors, you can do something like this:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try<br />
{<br />
&nbsp; </span><span class="default">$connection </span><span class="keyword">= </span><span class="default">mysql_connect</span><span class="keyword">(...);<br />
&nbsp; if (</span><span class="default">$connection </span><span class="keyword">=== </span><span class="default">false</span><span class="keyword">)<br />
&nbsp; {<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'Cannot connect do mysql'</span><span class="keyword">);<br />
&nbsp; }<br />
<br />
&nbsp;&nbsp; </span><span class="comment">/* ... do whatever you need with database, that may mail and throw exceptions too ... */<br />
<br />
&nbsp;&nbsp; </span><span class="default">mysql_close</span><span class="keyword">(</span><span class="default">$connection</span><span class="keyword">);<br />
}<br />
catch (</span><span class="default">Exception $e</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp; </span><span class="comment">/* ... add logging stuff there if you need ... */<br />
<br />
&nbsp; </span><span class="keyword">echo </span><span class="string">"This page cannot be displayed"</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
By doing so, you're aiming at the don't repeat yourself (D.R.Y) concept, by managing error handling at only one place for the whole.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="72567""></a>
  <div class="note">
   <strong class="user">jon at hackcraft dot net</strong>
   <a href="#72567" class="date">24-Jan-2007 06:52</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Further to dexen at google dot me dot up with "use destructors to perform a cleanup in case of exception". The fact that PHP5 has destructors, exception handling, and predictable garbage collection (if there's a single reference in scope and the scope is left then the destructor is called immediately) allows for the use of the RAII idiom.<br />
<br />
<a href="http://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization and my own http://www.hackcraft.net/RAII/ describe this." rel="nofollow" target="_blank">http://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization and my own http://www.hackcraft.net/RAII/ describe this.</a></span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="68697""></a>
  <div class="note">
   <strong class="user">jazfresh at hotmail.com</strong>
   <a href="#68697" class="date">08-Aug-2006 07:18</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Sometimes you want a single catch() to catch multiple types of Exception. In a language like Python, you can specify multiple types in a catch(), but in PHP you can only specify one. This can be annoying when you want handle many different Exceptions with the same catch() block.<br />
<br />
However, you can replicate the functionality somewhat, because catch(&lt;classname&gt; $var) will match the given &lt;classname&gt; *or any of it's sub-classes*.<br />
<br />
For example:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">DisplayException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br />
class </span><span class="default">FileException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{};<br />
class </span><span class="default">AccessControl </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br />
</span><span class="keyword">class </span><span class="default">IOError </span><span class="keyword">extends </span><span class="default">FileException </span><span class="keyword">{}; </span><span class="comment">// Sub-class of FileException<br />
<br />
</span><span class="keyword">try {<br />
&nbsp; if(!</span><span class="default">is_readable</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br />
&nbsp;&nbsp; &nbsp; throw new </span><span class="default">IOError</span><span class="keyword">(</span><span class="string">"File is not readable!"</span><span class="keyword">);<br />
&nbsp; if(!</span><span class="default">user_has_access_to_file</span><span class="keyword">(</span><span class="default">$someuser</span><span class="keyword">, </span><span class="default">$somefile</span><span class="keyword">))<br />
&nbsp;&nbsp; &nbsp; throw new </span><span class="default">AccessControl</span><span class="keyword">(</span><span class="string">"Permission denied!"</span><span class="keyword">);<br />
&nbsp; if(!</span><span class="default">display_file</span><span class="keyword">(</span><span class="default">$somefile</span><span class="keyword">))<br />
&nbsp;&nbsp; &nbsp; throw new </span><span class="default">DisplayException</span><span class="keyword">(</span><span class="string">"Couldn't display file!"</span><span class="keyword">);<br />
<br />
} catch (</span><span class="default">FileException $e</span><span class="keyword">) {<br />
&nbsp; </span><span class="comment">// This block will catch FileException, AccessControl or IOError exceptions, but not Exceptions or DisplayExceptions.<br />
&nbsp; </span><span class="keyword">echo </span><span class="string">"File error: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">();<br />
&nbsp; exit(</span><span class="default">1</span><span class="keyword">);<br />
}<br />
</span><span class="default">?&gt;<br />
</span><br />
Corollary: If you want to catch *any* exception, no matter what the type, just use "catch(Exception $var)", because all exceptions are sub-classes of the built-in Exception.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="65203""></a>
  <div class="note">
   <strong class="user">fjoggen at gmail dot com</strong>
   <a href="#65203" class="date">26-Apr-2006 10:58</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
This code will turn php errors into exceptions:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">exceptions_error_handler</span><span class="keyword">(</span><span class="default">$severity</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$filename</span><span class="keyword">, </span><span class="default">$lineno</span><span class="keyword">) { <br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$severity</span><span class="keyword">, </span><span class="default">$filename</span><span class="keyword">, </span><span class="default">$lineno</span><span class="keyword">); <br />
}<br />
<br />
</span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">'exceptions_error_handler'</span><span class="keyword">);<br />
</span><span class="default">?&gt;<br />
</span><br />
However since <span class="default">&lt;?php set_error_handler</span><span class="keyword">()</span><span class="default">?&gt;</span> doesn't work with fatal errors, you will not be able to throw them as Exceptions.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
